Add default param handling, Remove Spring dependency
arxes-tolina/annotation-validator pull request #1
Opened 2017-12-13 11:58 UTC by Signavio-math

Adds the following features
* Add new Only semantic next to Exactly semantic
  * default: asserts that configured annotations and params are present. Default values for not configured params are considered.
  * only: assert that only the configured annotations are present. Default values for not configured params are considered.
  * exactly: assert that only the configured annotations and params are present. No default values are considered.
* Removed all Spring dependencies from production code. The dependencies are still present in test scope. All reflection based 
* proper evaluation of AliasFor annotated fields/methods

2017-12-15 12:00 UTC, ghost requested changes

2017-12-15 12:00 UTC, 6ff334e commented on src/main/java/de/tolina/common/validation/AnnotationValidation.java
> +				e.printStackTrace();
Please handle Exceptions.

2017-12-15 12:00 UTC, 6ff334e commented on src/main/java/de/tolina/common/validation/AnnotationValidation.java
> +					e.printStackTrace();
Please handle Exceptions.

2017-12-15 12:00 UTC, 6ff334e commented on src/main/java/de/tolina/common/validation/AnnotationValidation.java
> +				e.printStackTrace();
Please handle Exceptions.

2017-12-15 12:00 UTC, 6ff334e commented on src/main/java/de/tolina/common/validation/AnnotationValidation.java
> +						e1.printStackTrace();
Please handle Exceptions.

2018-01-03 07:00 UTC, Signavio-math reviewed
reflection exceptions now lead to failing tests

2018-01-05 14:25 UTC, ghost approved these changes

2018-01-05 14:26 UTC, merged